export const teamMembers = [
    {
      name: "Jorge Eduardo ",
      position: "Desarrollador",
      image: "/img/jorge.jpg",
      twitter: "https://twitter.com/usuario",
      linkedin: "https://linkedin.com/in/usuario",
      github: "https://github.com/usuario",
      email: "usuario@example.com",
    },
    {
      name: "Luis Vargas",
      position: "Desarrollador",
      image: "/img/luis.jpg",
      twitter: "https://twitter.com/usuario",
      linkedin: "https://linkedin.com/in/usuario",
      email: "usuario@example.com",
      github: "https://github.com/usuario",
      email: "usuario@example.com",
    },
    {
        name: "Efrain Martinez",
        position: "Desarrollador",
        image: "/img/efra.jpg",
        twitter: "https://twitter.com/usuario",
        linkedin: "https://linkedin.com/in/usuario",
        github: "https://github.com/usuario",
        email: "usuario@example.com",
      },
      {
        name: "Joan Lopez",
        position: "Desarrollador",
        image: "/img/joan.jpg",
        twitter: "https://twitter.com/usuario",
        linkedin: "https://linkedin.com/in/usuario",
        github: "https://github.com/usuario",
        email: "usuario@example.com",
      },
      {
        name: "Alejandro Rousse",
        position: "Desarrollador",
        image: "/img/rousse.jpg",
        twitter: "https://twitter.com/usuario",
        linkedin: "https://linkedin.com/in/usuario",
        github: "https://github.com/usuario",
        email: "usuario@example.com",
      },
    
  ];
  